name: Build and Deploy

on:
  push:
    branches: [ main, stage ]
  pull_request:
    branches: [ main, stage ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Test build the image
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v7
        with:
          load: true
          push: false
          tags: ghcr.io/b-zago/scorevault/webserver:test

      - name: Short SHA
        if: ${{ github.event_name == 'push' }}
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v7
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/b-zago/scorevault/webserver:latest
            ghcr.io/b-zago/scorevault/webserver:${{ steps.sha.outputs.sha }}

  deploy:
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/b-zago/scorevault/webserver
    steps:
      - name: Checkout k3s-cluster repo
        uses: actions/checkout@v6
        with:
          repository: b-zago/k3s-cluster
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update image tag
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            VALUES_FILE="charts/scorevault/values-prod.yml"
          else
            VALUES_FILE="charts/scorevault/values-stage.yml"
          fi
          sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.sha }}|" $VALUES_FILE
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add $VALUES_FILE
          git commit -m "${{ github.ref_name }}: update scorevault webserver to ${{ needs.build.outputs.sha }}"
          git push
